### ISSUE TITLE
RM2 Pro Plus2

### ISSUE THREAD

**Issue by slasktrat** [RWensveen/com.broadlink#1]
Hi

Thanks for a great app, I can confirm that it is working for the RM2 Pro as well :)

var ExpectedDeviceID = 10119;  // RM2 Pro Plus2

**Comment by RWensveen** [comment]
Thanks for the info. 
Currently I am working on support for other devices. Only problem is that I cannot test them, as I only have a RM3 mini available.
There is a list of devices which might work (and problaly will). All supported devices+ID's are listed in lib/DeviceInfo.js

**Comment by BibiMaxx** [comment]
Hi Remko
I tried the RM2 Pro and it doesn't work. I got the message "other device found: RM2 PRO PLUS (10026)and then i want to add it i got the message no device found. Is the device on and is it connected to Wi-Fi network? 
My device is on and is connected to the network.

**Comment by RWensveen** [comment]
@BibiMaxx : the app currently only supports RM3 Mini. I am working on support for other devices, such as RM2 Pro, RM2 Pro Plus, A1, etc.
It should be available in the app in a few days.

So, you did not see an error: your device was detected correctly (so, wifi is working perfectly :-)
)

**Comment by RWensveen** [comment]
The latest version (on github, and soon in homeys app store) should solve these issues. 
Note however, RF might not be working. I now have a RM-pro-plus, but it looks like broadlink changes the commands compared to the previous version. I'll look into it a.s.a.p
