### ISSUE TITLE
RF433 RM3 Pro Plus doesn't learn

### ISSUE THREAD

**Issue by viixxiiv** [RWensveen/com.broadlink#10]
I've pressed the Learn RF command and the RM3 ProPlus lights up orange but clicking on all my RF remotes yields no learning function. How do I get it to work?

**Comment by viixxiiv** [comment]
Ok, managed to learn the RF. Somehow I could get it to store RF unless I already have an IR stored.

I also found that after storing an RF, the app and my RM3 pro plus loses connection. I have to restart the app and pull the plug in order to learn another RF signal.

After storing 3 RF codes, I did my flows and realise non the the RF fires.

**Comment by RWensveen** [comment]
Works as of version 2.0.2
