### ISSUE TITLE
Is the "homey:manager:api" permission actually required?

### ISSUE THREAD

**Issue by robertklep** [RWensveen/com.broadlink#11]
This permission is stated in [`app.json`](https://github.com/RWensveen/com.broadlink/blob/bd1fa75cf315f9120e074b14bbb01a4fba42ab8b/app.json#L20), but I don't see a particular reason why this permission is being requested.

The downside of requesting it is that new users will get a warning about it, which could lead to confusion (see [this forum post](https://community.athom.com/t/gain-full-access-to-homey-to-control-everything-on-behalf-of-the-user-notification/1303), for instance).

**Comment by RWensveen** [comment]
Not that I know of. I don't think it is required.
It will be removed.
