### ISSUE TITLE
Unused Permission "Gain access to homey to control everything on behalf of the user"

### ISSUE THREAD

**Issue by Timmmeeeeh** [RWensveen/com.broadlink#15]
I hope this permission could still be removed like you mentioned on the athom community forum: https://community.athom.com/t/gain-full-access-to-homey-to-control-everything-on-behalf-of-the-user-notification/1303
Because i would love to use your nice app 😄 
Thank you in advance,
Tim  😄

**Comment by RWensveen** [comment]
Removed permission in version 2.0.1
