### ISSUE TITLE
Hysen support

### ISSUE THREAD

**Issue by RetroTrek** [RWensveen/com.broadlink#16]
Hi there,

I have a thermostat that, like loads of cheap chinese thermostats, works on the broadlink platform.
When I use your app and try to add it it indeed says, other device found. Hysen.

Are you planning to write support for it? 

Thanks!

**Comment by RWensveen** [comment]
Hello,
I can have a look at an implementation for the Hysen thermostat (there is a nice implementation in python-broadlink I can rework). 
But as I do not own one, I have no way of testing if it works. I can even not guarantee the app won't crash if you try anything with the thermostat.

**Comment by RetroTrek** [comment]
Hi!
I have a little knowledge in programming, but I cannot write something like this.
What I can do is debug an existing app and see what goes wrong, and change little things.

So If the basis is there in the Homey app, I can help debug it without a problem.

**Comment by RWensveen** [comment]
Hysen thermostat now fully working in V2.0.4
