### ISSUE TITLE
Web-API

### ISSUE THREAD

**Issue by BibiMaxx** [RWensveen/com.broadlink#17]
Hi Remco,

You know Homey will bring out Homey V2. My question is to you is the broadlink app Web-API or must you rewrite the App to Web-API. If not will you rewrite the App?

Best regards 

Ben

**Comment by RWensveen** [comment]
Hello, the Broadlink App is not a Web-API app. Its latest version (2.0.1, currently in beta), is compatible with Homey V2

**Comment by BibiMaxx** [comment]
Hi Renko

Thanks that it works with Homey 2.0

Ben

Op ma 21 jan. 2019 22:58 schreef RWensveen <notifications@github.com:
