### ISSUE TITLE
Addin RF transmitter

### ISSUE THREAD

**Issue by Krillmcrall** [RWensveen/com.broadlink#18]
Hi 
I'm trying to get my RM Mini 3 to send a command to lower and rise the projector screen. I have an RF remote today, and it get's into e-control just fine, but for some reason I can't get it to register through Homey.

Any advice on how to solve this?

Thanks
K

**Comment by Voxen1** [comment]
Similar problem. The code is scanned, but not sent. Through the application broadlink Works

**Comment by RWensveen** [comment]
Works as of version 2.0.2.
See app description on how to use it.

**Comment by Voxen1** [comment]
Updated the application, now I can not record the RF signal (
