### ISSUE TITLE
Two Broadlink Devices Issue

### ISSUE THREAD

**Issue by Thenorneron** [RWensveen/com.broadlink#2]
When adding new device it replaces the old one so the old stops working and all commands are replaced with new one (in Flow tab). Although there are two devices in the Devices list and have own commands, in FLOWS it only shows one set of commands (new ones).

**Comment by RWensveen** [comment]
This is an error in the flows :-(
It will solved in version 1.1.1-beta :-)

**Comment by RWensveen** [comment]
Correction: solved in v1.1.2-beta
