### ISSUE TITLE
can't add broadlink

### ISSUE THREAD

**Issue by FLH-Henry** [RWensveen/com.broadlink#22]
I can't add Broadlink RM pro+ from Homey
Please refer to the figure below or the attachment.
![screenshot_20190221-160238](https://user-images.githubusercontent.com/16569175/53153828-3771ad80-35f4-11e9-9272-9ece66ad5093.png)
![router](https://user-images.githubusercontent.com/16569175/53153859-49ebe700-35f4-11e9-8757-65a7c1611be5.jpg)

Many thanks.

**Comment by RWensveen** [comment]
The ID of the device you are trying to add (10179) is not supported by the broadlink app. 
However, it is possible to forcefully add a broadlink device, even if the ID is not recognized.
- go to the app settings.
- enable the first option 'compatibility mode'.
- go to 'add devices', select Broadlink app
- select the device you want to add (in your case, the RM Pro Plus).

Whatever the ID of you device is, it will now be added to Homey as an RM Pro Plus.

A small warning: with this method, you can even add a SP1 (wall switch) as an RM Pro Plus. 
This will result in rather strange behaviour: after all, how can an RM Pro Plus device toggle 
its non-existing switch ?  :-)

**Comment by FLH-Henry** [comment]
OK,I have add successfully.
But,I can't find any button from Homey.
My Broadlink have two IR button.

Please refer to the figure below.
This image is from Homey app.
![screenshot_20190222-111239](https://user-images.githubusercontent.com/16569175/53217953-18772800-3695-11e9-912f-42d6c8d34e28.png)
![screenshot_20190222-111245](https://user-images.githubusercontent.com/16569175/53217957-1ad98200-3695-11e9-8e10-7e8fbe06270b.png)

This image is from Broadlink app.
![screenshot_20190222-111516](https://user-images.githubusercontent.com/16569175/53218006-55dbb580-3695-11e9-8d64-a8b3dc138cb5.png)

Please help,
Many thanks.
