### ISSUE TITLE
I can't find any button

### ISSUE THREAD

**Issue by FLH-Henry** [RWensveen/com.broadlink#23]
I have add Broadlink.
But,I can't find any button from Homey.
My Broadlink have two IR button.

Please refer to the figure below.
This image is from Homey app.
![screenshot_20190222-111239](https://user-images.githubusercontent.com/16569175/53217953-18772800-3695-11e9-912f-42d6c8d34e28.png)
![screenshot_20190222-111245](https://user-images.githubusercontent.com/16569175/53217957-1ad98200-3695-11e9-8e10-7e8fbe06270b.png)

This image is from Broadlink app.
![screenshot_20190222-111516](https://user-images.githubusercontent.com/16569175/53218006-55dbb580-3695-11e9-8d64-a8b3dc138cb5.png)

Please help,
Many thanks.

**Comment by RWensveen** [comment]
An extensive manual on how to use learing and commands is now available at   [https://community.athom.com/t/broadlink-app/6389](https://community.athom.com/t/broadlink-app/6389)
