### ISSUE TITLE
To send the command several times

### ISSUE THREAD

**Issue by ghost** [RWensveen/com.broadlink#25]
It would be convenient to send a command using N (based on a given variable) times using RM-pro (RM-mini).
Example: we know the set temperature and want to increase it by the calculated variable (+10). Send a command 10 times with a delay of 0.3 seconds

**Comment by RWensveen** [comment]
you can do so in a flow: add the required number of action-cards in the 'then' block. Use an increasing delay of 1 sec for each card.

**Comment by ghost** [comment]
this path, when you clearly know how many teams need to to hand. And if you need a dynamic number of times (i.e. calculated by a logical formula)?
