### ISSUE TITLE
Where are the codes stored?

### ISSUE THREAD

**Issue by Groschl** [RWensveen/com.broadlink#26]
Ok, I've managed to learn some IR codes to the Broadlink device instead of the RF ones which didn't work and can use them in the Homey app. However....if for some reason I need to reinstall the app, the codes are gone. Any idea where the codes are stored so I can save them?

**Comment by RWensveen** [comment]
The IR/RF codes are stored on your Homey, in the userdata folder of the app. For each IR/RF capable device, a file is created, where all commands are stored in JSON format.
If you reinstall the app without removing  it first, all apps devices remain intact, as well as the IR/RF data files. Removing a device also removes the data file.
There is currently no way to backup the files, or the commands stored in it.
