### ISSUE TITLE
Hi, can you push updates to Athom-Homey?

### ISSUE THREAD

**Issue by Thenorneron** [RWensveen/com.broadlink#3]
Latest beta there is v1.1.0, can you push updates (v.1.1.2) bc I tried manually installing but it crashes for me... Thanks for your work!

**Comment by Thenorneron** [comment]
@RWensveen I tried again manually with 1.2.0. and 1.1.2. and error again :( can you please help?

**Comment by RWensveen** [comment]
version 1.3.0 is available on github, and is submitted to Athom for approval :-)
