### ISSUE TITLE
RF433

### ISSUE THREAD

**Issue by edsallo** [RWensveen/com.broadlink#9]
New Broadlink Pro Plus 2018. s/n RM33xxxx. The RF433 code is read and stored. But through Flow can not be played.

**Comment by viixxiiv** [comment]
Same issue. RF doesn’t fire in any of my flows

**Comment by skarotech** [comment]
Same issue here too, new RM2 Pro Plus, seems to learn fine but will not replay thru flows, any way to better debug this issue to provide any info required to fix it ??

**Comment by JMeinen69** [comment]
same here.... rm2 pro plus. Learning and storing cmd code in app look oke. But when i trie to run them in a flow or linked to a virtual switch nothing happens. Anny clues? Why no answer from developer?

**Comment by trollen85** [comment]
Same here i have the newest Broadlink RM PRO+, It detects and store the rf signal as cmd1 cmd2 etc. but in flows when i try to pair it with virtual devices or anything else it dosen´t work. Please devolper fix this issue I bought this produt just for homey.

**Comment by RWensveen** [comment]
Learning commands is rather tricky: see [https://community.athom.com/t/broadlink-app/6389](https://community.athom.com/t/broadlink-app/6389)

**Comment by RWensveen** [comment]
Note that sometimes the commands sent by an RF remote contain time codes or counters. These are not supported by the RM Pro plus (and the like).
